-- S3 — Gross Revenue Retention (GRR) & Net Revenue Retention (NRR)
-- Owner: Adyasha | Last Updated: 2026-07-28
--
-- Business Question:
-- Of the MRR generated by each monthly revenue cohort, how much revenue was
-- retained 12 months later, both before and after accounting for expansion?

-- Assumption:
-- Revenue cohorts are defined as the month an account first generated positive
-- MRR. Starting and 12-month MRR are measured using month-end snapshots
-- (implemented as the first instant of the following month) by summing all
-- active subscriptions for each account.

-- PM Action:
-- Prioritize retention efforts for cohorts with GRR below 80% by analyzing
-- churn across acquisition channel, plan and company size. For cohorts with
-- NRR above 110%, identify the expansion drivers (plan upgrades, seat growth
-- or add-ons) and replicate those motions across similar customer segments.

-- Sanity Checks:
-- 1. grr <= 1.0
-- 2. nrr may exceed 1.0
-- 3. Cohorts are included only after a full 12-month observation window.

with first_paid_cohorts as (

    select
        s.account_id
      , date_trunc(
            'month'
          , min(s.start_date)
        )::date as cohort_month
    from saas.subscriptions as s
    where s.mrr > 0
    group by
        s.account_id

)

, snapshot_dates as (

    select
        fpc.account_id
      , fpc.cohort_month
      , (
            fpc.cohort_month
            + interval '1 month'
        ) as cohort_snapshot_at
      , (
            fpc.cohort_month
            + interval '13 month'
        ) as retention_snapshot_at
    from first_paid_cohorts as fpc

)

, account_snapshot_mrr as (

    select
        sd.account_id
      , sd.cohort_month

      , coalesce(

            sum(s.mrr) filter (

                where s.start_date < sd.cohort_snapshot_at
                  and (
                        s.end_date is null
                     or s.end_date >= sd.cohort_snapshot_at
                  )

            )

        , 0) as starting_mrr

      , coalesce(

            sum(s.mrr) filter (

                where s.start_date < sd.retention_snapshot_at
                  and (
                        s.end_date is null
                     or s.end_date >= sd.retention_snapshot_at
                  )

            )

        , 0) as ending_mrr

    from snapshot_dates as sd

    left join saas.subscriptions as s
        on sd.account_id = s.account_id

    group by
        sd.account_id
      , sd.cohort_month

)

, account_retention as (

    select
        asm.account_id
      , asm.cohort_month
      , asm.starting_mrr
      , asm.ending_mrr

      , least(
            asm.starting_mrr
          , asm.ending_mrr
        ) as retained_mrr

      , greatest(
            asm.ending_mrr
          - asm.starting_mrr
        , 0) as expansion_mrr

      , greatest(
            asm.starting_mrr
          - asm.ending_mrr
        , 0) as contraction_mrr

      , case
            when asm.ending_mrr = 0
                then asm.starting_mrr
            else 0
        end as churn_mrr

    from account_snapshot_mrr as asm

)

select
    ar.cohort_month

  , round(
        sum(ar.starting_mrr)::numeric
    , 2) as cohort_starting_mrr

  , round(
        sum(ar.retained_mrr)::numeric
    , 2) as retained_mrr_12m

  , round(
        sum(ar.expansion_mrr)::numeric
    , 2) as expansion_mrr_12m

  , round(
        sum(ar.contraction_mrr)::numeric
    , 2) as contraction_mrr_12m

  , round(
        sum(ar.churn_mrr)::numeric
    , 2) as churn_mrr_12m

  , round(
        (
            sum(ar.retained_mrr)
            / nullif(
                sum(ar.starting_mrr)
            , 0)
        )::numeric
    , 3) as grr

  , round(
        (
            sum(ar.retained_mrr)
          + sum(ar.expansion_mrr)
          - sum(ar.contraction_mrr)
        )
        / nullif(
            sum(ar.starting_mrr)
        , 0)::numeric
    , 3) as nrr

from account_retention as ar

where
    ar.cohort_month + interval '12 months'
    <= current_date

group by
    ar.cohort_month

order by
    ar.cohort_month;